version: "3.8"
services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    container_name: mongo
    volumes:
      - ./patent_jsons:/docker-entrypoint-initdb.d:ro
    ports:
      - "27017:27017"

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_app
    command: uvicorn app:app --host 0.0.0.0 --port 8000  # Add the desired command here
    ports:
      - "8000:8000"
    depends_on:
      - mongo
